### PR TITLE
Create barebones user interaction and prompts.

### PR DESCRIPTION
**Pull request by pointerish**
This PR implements the following:

- Basic player interaction and prompts on `main.rb`

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @pointerish
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##
Kindly work on the suggested changes  👇.
- [ ] Game asks players for their names ([screenshot hint](https://user-images.githubusercontent.com/29689273/98098521-44a9fb00-1eb0-11eb-8fa2-6e8601422c46.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [ ] Game tells which player turn it is (without computing who the winner is)([screenshot hint](https://user-images.githubusercontent.com/29689273/98098521-44a9fb00-1eb0-11eb-8fa2-6e8601422c46.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [ ] Game asks the player to select from available moves([screenshot hint](https://user-images.githubusercontent.com/29689273/98098521-44a9fb00-1eb0-11eb-8fa2-6e8601422c46.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [ ] Game informs player if the selected move is invalid (without computing what an invalid move is)([screenshot hint](https://user-images.githubusercontent.com/29689273/98098521-44a9fb00-1eb0-11eb-8fa2-6e8601422c46.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [ ] Game displays board after the player move (without computing which spots on the board are taken)([screenshot hint](https://user-images.githubusercontent.com/29689273/98098521-44a9fb00-1eb0-11eb-8fa2-6e8601422c46.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [ ] Game informs player if the selected move is a winning move (without computing the winning move)([screenshot hint](https://user-images.githubusercontent.com/29689273/98098521-44a9fb00-1eb0-11eb-8fa2-6e8601422c46.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [ ] Game informs player if the selected move is a draw move (without computing draw)([screenshot hint](https://user-images.githubusercontent.com/29689273/98098521-44a9fb00-1eb0-11eb-8fa2-6e8601422c46.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [ ] Game repeats all actions for the next player's move([screenshot hint](https://user-images.githubusercontent.com/29689273/98098521-44a9fb00-1eb0-11eb-8fa2-6e8601422c46.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by PhillipUg — CHANGES_REQUESTED** [review]
Hey **Josias Alvarado Gutierrez**, 👋

You have done a great job on this project so far! 

However, there are still some changes you need to make before you can move on to the next milestone

### Changes Required ♻️ 

- [ ] As stated by the previous reviewer, you need to display a game board instead of simply displaying `Showing board`
> - [ ] Game displays board after the player move 

- [ ] Currently, you're asking the player to select where to move but with no instructions on how to move.

### Optional Changes:

If you want to make your project even better 🔥💥 you can implement the following:
These are completely [Optional]: 🦔

- [ ] Instead of using `9.times do |turn|` for looping, you can use a terminating variable instead as illustrated below;

```
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end

```

#### Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack **Phillip Musiime**
I would be happy to help! 👩‍💻 

Happy coding 🤓

**Comment by pointerish** [comment]
Hi TSEs,

The changes requested were made except for the last one where the previous TSE suggested me to implement a sentinel loop. I feel that's not needed since it's a fact that the game won't take longer than 9 moves to reach a draw. 
Thanks for all the help!

Regards
Josias Alvarado

**Review by tirthajyoti-ghosh — APPROVED** [review]
# Approved ✅

## You have done an incredible job making this project 👏🧨💪! Just perfect 💯! 

### You have met all the requirements of the project. Go ahead and merge it! Onto the next project 🚀 !

Happy coding 👨‍💻 

<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Pull request merged**
